TouristAgency/SAM.TouristAgency.WEB/Areas/Admin/Controllers/HotelImageController.cs
using SAM.TouristAgency.BLL.Interfaces;
using SAM.TouristAgency.Model.ViewModels.Hotel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAM.TouristAgency.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HotelImageController : Controller
    {
        private readonly IHotelImageService _hotelImageService;
        private readonly IHotelService _hotelService;

        public HotelImageController(IHotelImageService hotelImageService, IHotelService hotelService)
        {
            _hotelImageService = hotelImageService;
            _hotelService = hotelService;
        }

        public ActionResult Index()
        {
            ViewBag.HotelList = _hotelService.GetAll();

            return View();
        }

        public JsonResult GetPaggedData(string sortType, int pageSize, int currentPage)
        {
            IEnumerable<HotelImageVM> pictures = _hotelImageService.GetTempHotels(sortType, pageSize, currentPage);

            var temp = from p in pictures
                       select new HotelImageVM
                       {
                           ImageId = p.ImageId,
                           ImagePath = Convert.ToBase64String(p.Image),
                           HotelId = p.HotelId,
                           HotelName = p.HotelName
                       };

            int allCount = _hotelImageService.Count();

            JsonResult json = Json(new { temp, allCount }, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;

            return json;
        }

        public ActionResult AddOrEdit(HotelImageVM model, HttpPostedFileBase UploadImage)
        {
            if (ModelState.IsValid && UploadImage != null)
            {
                byte[] imageData = null;

                using (var binaryReader = new BinaryReader(UploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(UploadImage.ContentLength);
                }

                model.Image = imageData;

                _hotelImageService.Create(model);
            }

            return RedirectToAction("Index");
        }

        public JsonResult Delete(int id)
        {
            string message = string.Empty;

            try
            {
                _hotelImageService.Delete(id);
                message = "Success";
            }
            catch (ApplicationException ex)
            {
                //logger.Error(ex.Message);
                message = ex.Message;
            }

            return Json(message, JsonRequestBehavior.AllowGet);
        }
    }
}

TouristAgency/SAM.TouristAgency.WEB/Areas/Admin/Views/HotelImage/Index.cshtml
@model SAM.TouristAgency.Model.ViewModels.Hotel.HotelImageVM
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <a href="#" class="btn btn-info my-2" onclick="AddNew()">Add New Hotel Image</a>

    <table class="table table-hover">
        <thead>
            <tr>
                <th><a href="#" class="text-warning" style="text-decoration:none" id="sortName">Image</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none" id="sortClass">Hotel</a></th>
                <th>Action(Delete)</th>
            </tr>
        </thead>
        <tbody id="HotelImageTable"></tbody>
    </table>

    <div id="paged" class="container my-5">
        <table>
            <tr>
                <td>
                    <select id="dropPageSize" class="form-control">
                        <option selected="selected">5</option>
                        <option>10</option>
                        <option>15</option>
                        <option>20</option>
                    </select>
                </td>
                <td>
                    <input type="button" class="btn btn-info" value="<<" id="btnFirst" />
                    <input type="button" class="btn btn-info" value="<" id="btnPre" />
                    <span><strong>Page</strong></span>
                    <input type="text" class="btn btn-warning" value="1" id="txbCurrentPage" style="width:50px;text-align:center;font-weight:bold;color:black" disabled />
                    <span><strong>Of</strong></span>
                    <input type="text" class="btn btn-warning" value="1" id="txbTotalPage" style="width:50px;text-align:center;font-weight:bold;color:black" disabled />
                    <input type="button" class="btn btn-info" value=">" id="btnNext" />
                    <input type="button" class="btn btn-info" value=">>" id="btnLast" />
                </td>
            </tr>
        </table>
    </div>


    <div class="modal fade" id="MyModal">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="ModalTitle">Add Hotel Image</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm("AddOrEdit", "HotelImage", FormMethod.Post, new { area = "Admin", @id = "myForm", enctype = "multipart/form-data" }))
                    {
                        <input type="hidden" name="ImageId" id="ImageId" value="0" />

                        <div>
                            <div class="form-group">
                                <label>Hotel</label>
                                <div>
                                    @Html.DropDownListFor(m => m.HotelId, new SelectList(ViewBag.HotelList, "HotelId", "Name"), "Select", new { @class = "form-control", @id = "DrpDown", required = "required" })
                                    @Html.ValidationMessageFor(model => model.HotelId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Image</label>
                                <div>
                                    <input type="file" class="form-control" name="UploadImage" required />
                                </div>
                            </div>
                            <div class="form-group mt-3">
                                <input type="submit" value="Save" class="btn btn-block btn-success" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="DeleteConfirmation">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Delete Image</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <h4>Are You Sure? You Want To Delete This Record.</h4>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                    <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/hotelimage")