TouristAgency/SAM.TouristAgency.WEB/Areas/Admin/Controllers/CommentController.cs
using Newtonsoft.Json;
using NLog;
using SAM.TouristAgency.BLL.Interfaces;
using SAM.TouristAgency.Model.ViewModels.Comment;
using System;
using System.Linq;
using System.Web.Mvc;

namespace SAM.TouristAgency.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CommentController : Controller
    {
        readonly Logger logger = LogManager.GetCurrentClassLogger();
        private readonly ICommentService _commentService;
        private readonly IAccountService _accountService;

        public CommentController(ICommentService commentService, IAccountService accountService)
        {
            _commentService = commentService;
            _accountService = accountService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAll()
        {
            return View();
        }

        public JsonResult GetPaggedDataAll(string sortType, int pageSize, int currentPage)
        {
            IQueryable<CommentVM> comments = _commentService.GetTempAllComments(sortType, pageSize, currentPage);

            int allCount = _commentService.Count();

            return Json(new { comments, allCount }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPaggedData(string sortType, int pageSize, int currentPage)
        {
            IQueryable<CommentVM> comments = _commentService.GetTempIsNotRightComments(sortType, pageSize, currentPage);

            int allCount = _commentService.Count();

            return Json(new { comments, allCount }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetById(int id)
        {
            string message = string.Empty;

            try
            {
                CommentVM comment = _commentService.GetById(id);

                message = JsonConvert.SerializeObject(comment, Formatting.Indented, new JsonSerializerSettings
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                });
            }
            catch (ApplicationException ex)
            {
                logger.Error(ex.Message);
                message = ex.Message;
            }

            return Json(message, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(CommentVM model)
        {
            string message = "The form did not pass validation";

            if (ModelState.IsValid)
            {
                try
                {
                    _commentService.Update(model);

                    message = "Success";
                }
                catch (ApplicationException ex)
                {
                    logger.Error(ex.Message);
                    message = ex.Message;
                }
            }

            return RedirectToAction("Index");
        }

        public JsonResult Delete(int id)
        {
            string message = string.Empty;

            try
            {
                _commentService.Delete(id);
                message = "Success";
            }
            catch (ApplicationException ex)
            {
                logger.Error(ex.Message);
                message = ex.Message;
            }

            return Json(message, JsonRequestBehavior.AllowGet);
        }
    }
}

TouristAgency/SAM.TouristAgency.WEB/Areas/Admin/Views/Comment/GetAll.cshtml
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th><a href="#" class="text-warning" style="text-decoration:none">Account name</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Tour name</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Message</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Date add</a></th>
                <th>Action(Delete)</th>
            </tr>
        </thead>
        <tbody id="CommentTable"></tbody>
    </table>

    <div id="paged" class="container my-5">
        <table>
            <tr>
                <td>
                    <select id="dropPageSize" class="form-control">
                        <option selected="selected">5</option>
                        <option>10</option>
                        <option>15</option>
                        <option>20</option>
                    </select>
                </td>
                <td>
                    <input type="button" class="btn btn-info" value="<<" id="btnFirst" />
                    <input type="button" class="btn btn-info" value="<" id="btnPre" />
                    <span><strong>Page</strong></span>
                    <input type="text" class="btn btn-warning" value="1" id="txbCurrentPage" style="width:50px;text-align:center;font-weight:bold;color:black" disabled />
                    <span><strong>Of</strong></span>
                    <input type="text" class="btn btn-warning" value="1" id="txbTotalPage" style="width:50px;text-align:center;font-weight:bold;color:black" disabled />
                    <input type="button" class="btn btn-info" value=">" id="btnNext" />
                    <input type="button" class="btn btn-info" value=">>" id="btnLast" />
                </td>
            </tr>
        </table>
    </div>

    <div class="modal fade" id="DeleteConfirmation">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Delete Hotel Record</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">

                    <input type="hidden" id="CommentId" />

                    <h4>Are You Sure? You Want To Delete This Record.</h4>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                    <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/allComment")

TouristAgency/SAM.TouristAgency.WEB/Areas/Admin/Views/Comment/Index.cshtml
@model SAM.TouristAgency.Model.ViewModels.Comment.CommentVM
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th><a href="#" class="text-warning" style="text-decoration:none">Account name</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Tour name</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Message</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Date add</a></th>
                <th>Action(Delete)</th>
            </tr>
        </thead>
        <tbody id="CommentTable"></tbody>
    </table>

    <div id="paged" class="container my-5">
        <table>
            <tr>
                <td>
                    <select id="dropPageSize" class="form-control">
                        <option selected="selected">5</option>
                        <option>10</option>
                        <option>15</option>
                        <option>20</option>
                    </select>
                </td>
                <td>
                    <input type="button" class="btn btn-info" value="<<" id="btnFirst" />
                    <input type="button" class="btn btn-info" value="<" id="btnPre" />
                    <span><strong>Page</strong></span>
                    <input type="text" class="btn btn-warning" value="1" id="txbCurrentPage" style="width:50px;text-align:center;font-weight:bold;color:black" disabled />
                    <span><strong>Of</strong></span>
                    <input type="text" class="btn btn-warning" value="1" id="txbTotalPage" style="width:50px;text-align:center;font-weight:bold;color:black" disabled />
                    <input type="button" class="btn btn-info" value=">" id="btnNext" />
                    <input type="button" class="btn btn-info" value=">>" id="btnLast" />
                </td>
            </tr>
        </table>
    </div>


    <div class="modal fade" id="MyModal">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="ModalTitle"></h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm("Edit", "Comment", FormMethod.Post, new { @id = "myForm", area = "Admin" }))
                    {
                        <input type="hidden" name="CommentId" id="CommentId" />
                        <input type="hidden" name="AccountId" id="AccountId" />
                        <input type="hidden" name="TourId" id="TourId" />

                        <div>
                            <div class="form-group">
                                <label class="control-lable">Account</label>
                                <div class="">
                                    <input type="text" name="AccountName" id="AccountName" class="form-control" readonly />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-lable">Tour</label>
                                <div class="">
                                    <input type="text" name="TourName" id="TourName" class="form-control" readonly />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-lable">Message</label>
                                <div class="">
                                    <textarea name="Message" id="Message" class="form-control" readonly></textarea>
                                </div>
                            </div>

                            <div class="form-group mt-3">
                                <input type="submit" value="Access" class="btn btn-block btn-success" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="DeleteConfirmation">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Delete Hotel Record</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <h4>Are You Sure? You Want To Delete This Record.</h4>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                    <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/comment")