TouristAgency/SAM.TouristAgency.WEB/Areas/Admin/Controllers/TourController.cs
using NLog;
using SAM.TouristAgency.BLL.Interfaces;
using SAM.TouristAgency.Model.ViewModels.Tour;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAM.TouristAgency.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TourController : Controller
    {
        readonly Logger logger = LogManager.GetCurrentClassLogger();
        private readonly ITourService _tourService;
        private readonly IHotelService _hotelService;

        public TourController(ITourService tourService, IHotelService hotelService)
        {
            _tourService = tourService;
            _hotelService = hotelService;
        }

        public ActionResult Index()
        {
            ViewBag.HotelList = _hotelService.GetAll();
            ViewBag.CountryList = GetCountries();

            return View();
        }

        public JsonResult GetPaggedData(string sortType, int pageSize, int currentPage)
        {
            IEnumerable<TourVM> tours = _tourService.GetTempTours(sortType, pageSize, currentPage);

            var temp = from t in tours
                       select new TourVM
                       {
                           TourId = t.TourId,
                           Cost = t.Cost,
                           Country = t.Country,
                           DateStart = t.DateStart,
                           Duration = t.Duration,
                           HotelId = t.HotelId,
                           HotelName = t.HotelName,
                           Name = t.Name,
                           Description = t.Description,
                           ImagePath = Convert.ToBase64String(t.Image)
                       };

            int allCount = _tourService.Count();

            JsonResult json = Json(new { temp, allCount }, JsonRequestBehavior.AllowGet);
            json.MaxJsonLength = int.MaxValue;

            return json;
        }

        [HttpPost]
        public ActionResult Create(TourVM model, HttpPostedFileBase UploadImage)
        {
            if (ModelState.IsValid && UploadImage != null)
            {
                byte[] imageData = null;

                using (var binaryReader = new BinaryReader(UploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(UploadImage.ContentLength);
                }

                model.Image = imageData;

                try
                {
                    _tourService.Create(model);
                }
                catch (ApplicationException ex)
                {
                    logger.Error(ex.Message);
                }
            }

            return RedirectToAction("Index");
        }

        public JsonResult Delete(int id)
        {
            string message = string.Empty;

            try
            {
                _tourService.Delete(id);
                message = "Success";
            }
            catch (ApplicationException ex)
            {
                logger.Error(ex.Message);
                message = ex.Message;
            }

            return Json(message, JsonRequestBehavior.AllowGet);
        }

        [NonAction]
        public static List<string> GetCountries()
        {
            var list = CultureInfo.GetCultures(CultureTypes.SpecificCultures).
                 Select(p => new RegionInfo(p.Name).EnglishName).
                 Distinct().OrderBy(s => s).ToList();

            return list;
        }
    }
}

TouristAgency/SAM.TouristAgency.WEB/Areas/Admin/Views/Tour/Index.cshtml
@model SAM.TouristAgency.Model.ViewModels.Tour.TourVM

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <a href="#" class="btn btn-info my-2" onclick="AddNew()">Add New Tour</a>

    <table class="table table-hover table-responsive">
        <thead>
            <tr>
                <th><a href="#" class="text-warning" style="text-decoration:none">Image</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Name ▼</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">DateStart ▼</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Duration ▼</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Cost ▼</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Country</a></th>
                <th><a href="#" class="text-warning" style="text-decoration:none">Hotel</a></th>
                <th>Action(Delete)</th>
            </tr>
            <tr>
                <td></td>
                <td><input type="text" placeholder="Name..." class="form-control" onkeyup="Search(this, 0)" style="width:100px" /></td>
                <td><input type="text" placeholder="DateStart..." class="form-control" onkeyup="Search(this, 1)" style="width:100px" /></td>
                <td><input type="text" placeholder="Duration..." class="form-control" onkeyup="Search(this, 2)" style="width:100px" /></td>
                <td><input type="text" placeholder="Cost..." class="form-control" onkeyup="Search(this, 3)" style="width:100px" /></td>
                <td><input type="text" placeholder="Country..." class="form-control" onkeyup="Search(this, 4)" style="width:100px" /></td>
                <td></td>
            </tr>
        </thead>
        <tbody id="TourTable"></tbody>
    </table>

    <div id="paged" class="container my-5">
        <table>
            <tr>
                <td>
                    <select id="dropPageSize" class="form-control">
                        <option selected="selected">5</option>
                        <option>10</option>
                        <option>15</option>
                        <option>20</option>
                    </select>
                </td>
                <td>
                    <input type="button" class="btn btn-info" value="<<" id="btnFirst" />
                    <input type="button" class="btn btn-info" value="<" id="btnPre" />
                    <span><strong>Page</strong></span>
                    <input type="text" class="btn btn-warning" value="1" id="txbCurrentPage" style="width:50px;text-align:center;font-weight:bold;color:black" disabled />
                    <span><strong>Of</strong></span>
                    <input type="text" class="btn btn-warning" value="1" id="txbTotalPage" style="width:50px;text-align:center;font-weight:bold;color:black" disabled />
                    <input type="button" class="btn btn-info" value=">" id="btnNext" />
                    <input type="button" class="btn btn-info" value=">>" id="btnLast" />
                </td>
            </tr>
        </table>
    </div>


    <div class="modal fade" id="MyModal">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="ModalTitle">Create Tour Record</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm("Create", "Tour", FormMethod.Post, new { @id = "myForm", area = "Admin", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div>

                            <input type="hidden" name="TourId" value="0" id="TourId" />

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @id = "Name" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.HotelId, htmlAttributes: new { @class = "control-label" })
                                <div>
                                    @Html.DropDownListFor(model => model.HotelId, new SelectList(ViewBag.HotelList, "HotelId", "Name"), "Select", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.HotelId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.DateStart, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control", @id = "Class" } })
                                    @Html.ValidationMessageFor(model => model.DateStart, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", @id = "Capacity" } })
                                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control", @id = "Capacity" } })
                                    @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label" })
                                <div>
                                    @Html.DropDownListFor(model => model.Country, new SelectList(ViewBag.CountryList), "Select", new { @class = "form-control", @id = "Country" })
                                    @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @id = "Description" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label">Image</label>
                                <div>
                                    <input type="file" class="form-control" id="UploadImage" name="UploadImage" required />
                                    @Html.ValidationMessage("UploadImage", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group mt-3">
                                <input type="submit" value="Submit" class="btn btn-block btn-success" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="DeleteConfirmation">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Delete Tour Record</h4>
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                </div>
                <div class="modal-body">
                    <h4>Are You Sure? You Want To Delete This Record.</h4>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                    <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/tour")