TouristAgency/SAM.TouristAgency.WEB/Areas/User/Controllers/OrderController.cs
using NLog;
using SAM.TouristAgency.BLL.Interfaces;
using SAM.TouristAgency.Model.ViewModels.Account;
using SAM.TouristAgency.Model.ViewModels.Order;
using SAM.TouristAgency.Model.ViewModels.Tour;
using System;
using System.Web.Mvc;

namespace SAM.TouristAgency.WEB.Areas.User.Controllers
{
    [Authorize(Roles = "User")]
    public class OrderController : Controller
    {
        Logger logger = LogManager.GetCurrentClassLogger();

        private readonly IOrderService _orderService;
        private readonly ITourService _tourService;
        private readonly IHotelService _hotelService;
        private readonly IAccountService _accountService;

        public OrderController(IOrderService orderService, ITourService tourService, IHotelService hotelService, IAccountService accountService)
        {
            _orderService = orderService;
            _tourService = tourService;
            _hotelService = hotelService;
            _accountService = accountService;
        }

        public ActionResult Booking(int tourId)
        {
            ViewBag.Tour = _tourService.GetById(tourId);

            return View();
        }

        [HttpPost]
        public ActionResult Booking(BookingVM model)
        {
            TourVM tour = _tourService.GetById(model.TourId);

            if (ModelState.IsValid)
            {
                if (model.Amount > tour.HotelCapacity)
                {
                    ViewBag.Message = "There is not enough space in the hotel";
                }
                else
                {
                    string email = User.Identity.Name;
                    AccountVM account = _accountService.GetByEmail(email);

                    model.AccountId = account.AccountId;

                    _orderService.NewOrder(model);

                    return Redirect("/User/Account/MyProfile");
                }
            }

            ViewBag.Tour = tour;

            return View(model);
        }

        public JsonResult CancelBooking(int orderId)
        {
            string message = string.Empty;

            try
            {
                _orderService.CancelOrder(orderId);
                message = "Success";
            }
            catch (ApplicationException ex)
            {
                logger.Error(ex.Message);
                message = ex.Message;
            }

            return Json(message, JsonRequestBehavior.AllowGet);
        }
    }
}

TouristAgency/SAM.TouristAgency.WEB/Areas/User/Views/Order/Booking.cshtml
@model SAM.TouristAgency.Model.ViewModels.Order.BookingVM
@{
    ViewBag.Title = "Booking";
    Layout = "~/Views/Shared/_DetailWithHeaderAndFooterLayout.cshtml";
}

<div class="row">
    <div class="col-md-6">
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                @ViewBag.Message
            </div>
        }


        @using (Html.BeginForm("Booking", "Order", FormMethod.Post, new { area = "User" }))
        {
            @Html.AntiForgeryToken()

            <input type="hidden" value="@ViewBag.Tour.TourId" name="TourId" id="TourId" />

            <div class="form-group">
                <label class="control-label">Amount</label>
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control col-auto", min = "1", value = "1" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Surname, Name, Patrpnymic</label>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control col-auto", placeholder = "Ivanov Ivan Ivanovich" } })
                <small>This field is optional</small>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label class="control-label">Passport series and number BLR</label>
                        @Html.EditorFor(model => model.Passport, new { htmlAttributes = new { @class = "form-control col-auto", placeholder = "BM XXXXXXX", maxlength = "9" } })
                        @Html.ValidationMessageFor(model => model.Passport, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label class="control-label">When issued</label>
                        @Html.EditorFor(model => model.DateIssued, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.DateIssued, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-check my-4">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
                <label class="form-check-label" for="defaultCheck1">
                    I agree with the processing of personal data
                </label>
            </div>
            <div class="form-group">
                <label class="control-label">Credit Card</label>
                <input type="text" class="form-control col-auto" disabled placeholder="XXXX-XXXX-XXXX-XXXX" maxlength="16" name="CreditCard" id="CreditCard" />
                @Html.ValidationMessageFor(model => model.CreditCard, "", new { @class = "text-danger" })
            </div>
            <input type="submit" value="Book" id="Book" disabled class="col-auto btn btn-block btn-outline-success" />
        }
    </div>
    <div class="col-md-6">
        <div class="card w-100">
            <div class="card-header">
                <h2 class="card-title">Description:</h2>
            </div>
            <div class="card-body">
                <h2 class="text-center">@ViewBag.Tour.Name</h2>
                <p><strong>Date start:</strong> @ViewBag.Tour.DateStart.ToShortDateString()</p>
                <p><strong>Country:</strong> @ViewBag.Tour.Country</p>
                <p><strong>Hotel capacity:</strong> @ViewBag.Tour.HotelCapacity</p>
                <p><strong>Duration:</strong> @ViewBag.Tour.Duration days</p>
                <h3>Cost: @ViewBag.Tour.Cost$</h3>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")

<script src="~/Scripts/MyScripts/User/Order.js"></script>